export default function item(){
    return(
        {
            type:"div",
            style:`
                {
                    display:flex;
                    flex-direction:row;
                    align-items:center;
                    height:23%;
                    width:100%;
                    box-shadow:0px 0px 2px 0px var(--colorWhite);
                    border-radius:10px;
                    overflow:hidden;
                }
                :responsive{
                    height:fit-content;
                    margin:5px 0px;
                }`,
            children:[
                {
                    type:"img",
                    style:`
                        {
                            height:100%;
                            aspect-ratio:1;
                        }
                        :responsive{
                            width:25vw;
                        }`,
                    src:"https://img.magnific.com/fotos-gratis/jovem-bonito-vestindo-camiseta-casual-sobre-o-rosto-feliz-de-fundo-azul-sorrindo-com-os-bracos-cruzados-olhando-para-a-camera-pessoa-positiva_839833-12963.jpg?semt=ais_hybrid&w=740&q=80",
                    alt:"Foto de um garoto"
                },
                {
                    type:"div",
                    style:`
                        {
                            display:flex;
                            flex-direction:column;
                            align-items:right;
                            width:100%;
                            padding:5px 10px;
                        }`,
                    children:[
                        {
                            type:"div",
                            style:`
                                {
                                    font-size:15px;
                                    color:var(--colorWhite);
                                    width:100%;
                                    text-align:right;
                                }`,
                            innerHTML:"13/09/2026"
                        },
                        {
                            type:"div",
                            style:`
                                {
                                    font-size:18px;
                                    font-weight:500;
                                    color:var(--colorWhite);
                                    width:100%;
                                }`,
                            innerHTML:"Palestra com Sr. Rubens Carvalho"
                        },
                        {
                            type:"div",
                            style:`
                                {
                                    font-size:13px;
                                    color:var(--colorWhite);
                                    width:100%;
                                }`,
                            innerHTML:"Sr. Rubens Carvalho é advogado"
                        }
                    ]
                }
            ]
        }
    )
}